CREATE TABLE DELIVERY_TBL(
    ID NUMBER PRIMARY KEY ,
    ADDRESS NVARCHAR2(100),
    SEND_TIME TIMESTAMP,
    DELIVERED_TIME TIMESTAMP,
    RECEIVER NVARCHAR2(30),
    DELIVER_STATUS NVARCHAR2(15),
    PAYMENT REFERENCES PAYMENT_TBL
);
CREATE SEQUENCE DELIVERY_SEQ START WITH 1 INCREMENT BY 1;