CREATE TABLE INVOICE_ITEM_TBL(
    ID NUMBER PRIMARY KEY,
    COUNT NUMBER,
    PRODUCT REFERENCES PRODUCT_TBL,
    INVOICE REFERENCES INVOICE_TBL
);
CREATE SEQUENCE INVOICE_ITEM_SEQ START WITH 1 INCREMENT BY 1;